name: First Workflow
on: push
jobs: 
  first-job:
    runs-on: ubuntu-latest  # Fixed: ubuntu-latest instead of ubuntu-lastest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
