name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest  # Fixed: ubuntu-latest instead of ubuntu-lastest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye  # Also fixed the typo in "goodbye"
        run: echo "Done - bye"
